/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as TricksRouteImport } from './routes/tricks'
import { Route as DrillConceptRouteImport } from './routes/drill.$concept'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizModeRouteImport } from './routes/quiz.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TricksRoute = TricksRouteImport.update({
  id: '/tricks',
  path: '/tricks',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillConceptRoute = DrillConceptRouteImport.update({
  id: '/drill/$concept',
  path: '/drill/$concept',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizModeRoute = QuizModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => QuizRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flashcards': typeof FlashcardsRoute
  '/learn': typeof LearnRouteWithChildren
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/tricks': typeof TricksRoute
  '/drill/$concept': typeof DrillConceptRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flashcards': typeof FlashcardsRoute
  '/progress': typeof ProgressRoute
  '/tricks': typeof TricksRoute
  '/drill/$concept': typeof DrillConceptRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/learn': typeof LearnIndexRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/flashcards': typeof FlashcardsRoute
  '/learn': typeof LearnRouteWithChildren
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/tricks': typeof TricksRoute
  '/drill/$concept': typeof DrillConceptRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators'
    | '/cheatsheet'
    | '/flashcards'
    | '/learn'
    | '/progress'
    | '/quiz'
    | '/tricks'
    | '/drill/$concept'
    | '/learn/$slug'
    | '/quiz/$mode'
    | '/learn/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators'
    | '/cheatsheet'
    | '/flashcards'
    | '/progress'
    | '/tricks'
    | '/drill/$concept'
    | '/learn/$slug'
    | '/quiz/$mode'
    | '/learn'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/calculators'
    | '/cheatsheet'
    | '/flashcards'
    | '/learn'
    | '/progress'
    | '/quiz'
    | '/tricks'
    | '/drill/$concept'
    | '/learn/$slug'
    | '/quiz/$mode'
    | '/learn/'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CheatsheetRoute: typeof CheatsheetRoute
  FlashcardsRoute: typeof FlashcardsRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRouteWithChildren
  TricksRoute: typeof TricksRoute
  DrillConceptRoute: typeof DrillConceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tricks': {
      id: '/tricks'
      path: '/tricks'
      fullPath: '/tricks'
      preLoaderRoute: typeof TricksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/$concept': {
      id: '/drill/$concept'
      path: '/drill/$concept'
      fullPath: '/drill/$concept'
      preLoaderRoute: typeof DrillConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/$mode': {
      id: '/quiz/$mode'
      path: '/$mode'
      fullPath: '/quiz/$mode'
      preLoaderRoute: typeof QuizModeRouteImport
      parentRoute: typeof QuizRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface QuizRouteChildren {
  QuizModeRoute: typeof QuizModeRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizModeRoute: QuizModeRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsRoute: CalculatorsRoute,
  CheatsheetRoute: CheatsheetRoute,
  FlashcardsRoute: FlashcardsRoute,
  LearnRoute: LearnRouteWithChildren,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRouteWithChildren,
  TricksRoute: TricksRoute,
  DrillConceptRoute: DrillConceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
